/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DLL.CheckKituDLL;
import DLL.UserDLL;
import Entity.User;
import java.util.ArrayList;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Aki
 */
public class GuiUser extends javax.swing.JFrame {

    /**
     * Creates new form GuiUser
     */
    ArrayList<User> listuser= new ArrayList<User>();
    UserDLL userdll= new UserDLL();
    
    CheckKituDLL checkdll= new CheckKituDLL();
    
    public GuiUser() {
        initComponents();
        Bliding();
         int row=tbshow.getRowCount();
       for(int i=1;i<row;i++){
           int max=Integer.parseInt(String.valueOf((tbshow.getValueAt(0, 0))));
            if(max<Integer.parseInt(String.valueOf(tbshow.getValueAt(i, 0)))){
                max=Integer.parseInt(String.valueOf(tbshow.getValueAt(i, 0)));
             
             // int ma1=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
               // txtmasp.setText(String.valueOf(ma1+1));
               //txtmasp.setText("");
            }
            max=max+1;
            txtIDKH.setText(String.valueOf(max));
        }
    }
    public void Bliding(){
    listuser=userdll.getAll();
        Vector clums= new Vector();
        clums.add("Mã khach hàng");
        clums.add("Ten khách hàng");
        clums.add("Số điện thoại");
        clums.add("Địa chỉ");
        clums.add("Tuổi");
        Vector data= new Vector();
        for(User us:listuser){
            Vector row= new Vector();
            row.add(us.getUserid());
            row.add(us.getFullname());
            row.add(us.getphone());
            row.add(us.getAddress());
            row.add(us.getage());
            data.add(row);
            
        }
        DefaultTableModel dtm = new DefaultTableModel(data,clums);
        tbshow.setModel(dtm);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbshow = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtfind = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Quản lý Khách hàng");

        tbshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbshowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbshow);

        jLabel2.setText("ID Khách hàng");

        jLabel3.setText("Tên khách hàng");

        jLabel4.setText("Số điện thoại");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Tuổi");

        txtIDKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKHKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKHKeyReleased(evt);
            }
        });

        txtTenKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenKHKeyReleased(evt);
            }
        });

        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSDTKeyPressed(evt);
            }
        });

        txtDiachi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiachiKeyReleased(evt);
            }
        });

        txtTuoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTuoiKeyPressed(evt);
            }
        });

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtfind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfindMouseClicked(evt);
            }
        });
        txtfind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfindKeyReleased(evt);
            }
        });

        jButton4.setText("Find");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenu3.setText("Thay đổi thông tin đăng nhập");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Info");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Thoát");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("Quản lý sàn phẩm");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Quản lý hóa đơn");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Quản lý hóa đơn chi tiết");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtIDKH)
                            .addComponent(txtSDT))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel1)
                .addGap(101, 101, 101)
                .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtIDKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbshowMouseClicked
        // TODO add your handling code here:
        if(tbshow.getSelectedRow()!=-1){
            int row=tbshow.getSelectedRow();
            txtIDKH.setText(String.valueOf(tbshow.getValueAt(row, 0)));
            txtTenKH.setText(String.valueOf(tbshow.getValueAt(row, 1)));
            txtSDT.setText(String.valueOf(tbshow.getValueAt(row, 2)));
            txtDiachi.setText(String.valueOf(tbshow.getValueAt(row, 3)));
            txtTuoi.setText(String.valueOf(tbshow.getValueAt(row, 4)));
            
        }
    }//GEN-LAST:event_tbshowMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        listuser= userdll.getAll(); 
        int userid=Integer.parseInt(txtIDKH.getText());
        String tenkh= txtTenKH.getText();
        String phone= txtSDT.getText();
        String Diachi=txtDiachi.getText();
        int Age=Integer.parseInt(txtTuoi.getText());
        
        User us= new User();
        us.setUserid(userid);
        us.setFulname(tenkh);
        us.setphone(phone);
        us.setaddress(Diachi);
        us.setage(Age);
        if(userdll.AddData(us)){
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            Bliding();
        }else{
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        listuser= userdll.getAll(); 
        int userid=Integer.parseInt(txtIDKH.getText());
        String tenkh= txtTenKH.getText();
        String phone= txtSDT.getText();
        String Diachi=txtDiachi.getText();
        int Age=Integer.parseInt(txtTuoi.getText());
        int row= tbshow.getSelectedRow();
        
        User us= new User();
        us.setUserid(listuser.get(row).getUserid());
        us.setFulname(tenkh);
        us.setphone(phone);
        us.setaddress(Diachi);
        us.setage(Age);
        if(userdll.UpdateData(us)){
        JOptionPane.showMessageDialog(this, "Update thành công");
        Bliding();
    }else{
            JOptionPane.showMessageDialog(this, "Update thât bại");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(tbshow.getSelectedRow()!=-1){
            int row=tbshow.getSelectedRow();
            listuser=userdll.getAll();
          
            if(userdll.DelData(listuser.get(row).getUserid())){
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                Bliding();
            }
            else{
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kq=JOptionPane.showConfirmDialog(null,"Bạn thật sự muốn thoát","Close",JOptionPane.YES_OPTION);
        if(kq==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String find = txtfind.getText();
        
             DefaultTableModel dtm= (DefaultTableModel)tbshow.getModel();
             dtm.fireTableDataChanged();
             TableRowSorter trs= new TableRowSorter(dtm);
             tbshow.setRowSorter(trs);
             trs.setRowFilter(RowFilter.regexFilter(find));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtfindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfindMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfindMouseClicked

    private void txtfindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyPressed
        // TODO add your handling code here:
     
        
             
    }//GEN-LAST:event_txtfindKeyPressed

    private void txtIDKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKHKeyPressed
        // TODO add your handling code here:x
        
        
    }//GEN-LAST:event_txtIDKHKeyPressed

    private void txtSDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyPressed
        // TODO add your handling code here:
        Pattern pattern =Pattern.compile("\\d*");
        Matcher matcher =pattern.matcher(txtSDT.getText());
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(this, "Số điện thọai là số","Warning",JOptionPane.WARNING_MESSAGE);
            txtSDT.requestFocus();
            txtIDKH.setText("");
        }
    }//GEN-LAST:event_txtSDTKeyPressed

    private void txtTuoiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTuoiKeyPressed
        // TODO add your handling code here:í
         Pattern pattern =Pattern.compile("\\d*");
        Matcher matcher =pattern.matcher(txtTuoi.getText());
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(this, "Tuổi là số","Warning",JOptionPane.WARNING_MESSAGE);
            txtTuoi.requestFocus();
            txtTuoi.setText("");
        }
    }//GEN-LAST:event_txtTuoiKeyPressed

    private void txtTenKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKHKeyReleased
        // TODO add your handling code here:
        if(checkdll.checksyb(txtTenKH.getText())){
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt");
            txtTenKH.setText("");
        }
    }//GEN-LAST:event_txtTenKHKeyReleased

    private void txtDiachiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiachiKeyReleased
        // TODO add your handling code here:
        if(checkdll.checksyb(txtDiachi.getText())){
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt");
            txtDiachi.setText("");
        }
    }//GEN-LAST:event_txtDiachiKeyReleased

    private void txtIDKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKHKeyReleased
        // TODO add your handling code here:
        Pattern pattern =Pattern.compile("\\d*");
        Matcher matcher =pattern.matcher(txtIDKH.getText());
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(this, "Mã là số","Warning",JOptionPane.WARNING_MESSAGE);
            txtIDKH.requestFocus();
            txtIDKH.setText("");
        }
        
       int row=tbshow.getRowCount();
      int ma= row+1;
       
       
     /*  if(Integer.parseInt( txtmasp.getText())<ma)
       {
           
           JOptionPane.showMessageDialog(this, "Mã tăng và không được trùng mã có sẵn!");
           txtmasp.setText(Integer.toString(ma));
       }*/
        for(int i=0;i<row;i++){
            if(txtIDKH.getText().equals(String.valueOf(tbshow.getValueAt(i, 0)))){
                JOptionPane.showMessageDialog(this,"Không được trùng mã");
             // int ma1=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
               // txtmasp.setText(String.valueOf(ma1+1));
               txtIDKH.setText("");
            }
        }
  
      
           
        
       
    }//GEN-LAST:event_txtIDKHKeyReleased

    private void txtfindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyReleased
        // TODO add your handling code here:
        DefaultTableModel dtm= (DefaultTableModel)tbshow.getModel();
             dtm.fireTableDataChanged();
             TableRowSorter trs= new TableRowSorter(dtm);
             tbshow.setRowSorter(trs);
             trs.setRowFilter(RowFilter.regexFilter(txtfind.getText()));
    }//GEN-LAST:event_txtfindKeyReleased

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
         QuenPass qp= new QuenPass();
        qp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Main ma= new Main();
        ma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        QLHOADON qlh= new QLHOADON();
        qlh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        GuiOrderDetail god= new GuiOrderDetail();
        god.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbshow;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtIDKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTuoi;
    private javax.swing.JTextField txtfind;
    // End of variables declaration//GEN-END:variables
}
