/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DLL.AccountDLL;
import DLL.CategoryDLL;
import DLL.CheckKituDLL;
import DLL.ProductDLL;
import DLL.UserDLL;
import Entity.Category;
import Entity.Product;
import Entity.User;
import java.util.ArrayList;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Aki
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    ProductDLL prodll = new ProductDLL();
    ArrayList<Product> listpro=new ArrayList<>();
    
    CategoryDLL catedll = new CategoryDLL();
    ArrayList<Category> listcate= new ArrayList<>();
    
    UserDLL userDLL = new UserDLL();
    ArrayList<User> listuser= new ArrayList<>();
    
    AccountDLL accdll = new AccountDLL();
    
    CheckKituDLL checkdll= new CheckKituDLL();
    
    public Main() {
        initComponents();
        Bliding();
        BlidingSize();
        BlidingCat();
        int row=tbproduct.getRowCount();
       for(int i=1;i<row;i++){
           int max=Integer.parseInt(String.valueOf((tbproduct.getValueAt(0, 0))));
            if(max<Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)))){
                max=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
             
             // int ma1=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
               // txtmasp.setText(String.valueOf(ma1+1));
               //txtmasp.setText("");
            }
            max=max+1;
            txtmasp.setText(String.valueOf(max));
        }
    }
    public void  Bliding()
    {
        listpro = prodll.getAll();
        Vector culms= new Vector();
        culms.add("Mã sản phâm");
        culms.add("Tên sản phẩm");
        culms.add("Nhãn hiệu");
        culms.add("Giá");
        culms.add("Số lượng");
        culms.add("Kích cỡ");
        culms.add("Category");
        
        Vector data= new Vector();
        for (Product pro : listpro) {
            Vector row = new Vector();
            row.add(pro.getproid());
            row.add(pro.getname());
            row.add(pro.getbrand());
            row.add(pro.getprice());
            row.add(pro.getquantity());
            
             listpro =prodll.getbyID(pro.getproid());
            try {
                if(listpro.size()>0){
                row.add(listpro.get(0).getDesc());}
                else{
                    row.add("Không có");
                }
            } catch (Exception e) {
                    e.printStackTrace();
                    }
           
            listcate=catedll.getByID(pro.getcatid());
            try{
            if(listcate.size()>0){
                row.add(listcate.get(0).getname());}
            else{
               row.add("Không có");
            }
            }catch(Exception e){
                e.printStackTrace();
                System.out.println("Ko có dư liệu!!!!!");
                    }
      
            
            
           
            
    
            
           
            
            
            data.add(row);
            
          //  row.add(pro.getDesc());
           // row.add(pro.getcatid());
            
        }
        DefaultTableModel dtm = new DefaultTableModel(data,culms);
        tbproduct.setModel(dtm);
    }
    public  void BlidingCat(){
    listcate = catedll.getAll();
    for(Category ca: listcate){
        cbCate.addItem(ca.getname());
    }
    
}
    public void BlidingSize(){
        listpro= prodll.getAll();
        
            cbSize.addItem("M");
            cbSize.addItem("S");
            cbSize.addItem("L");
            cbSize.addItem("X");
            cbSize.addItem("XL");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproduct = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttensp = new javax.swing.JTextField();
        txtbrand = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        txtgia = new javax.swing.JTextField();
        cbSize = new javax.swing.JComboBox<>();
        cbCate = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtmasp = new javax.swing.JTextField();
        txtfind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("jMenu5");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Quản lý shop quần áo");

        tbproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbproduct);

        jLabel2.setText("Tên sản phẩm");

        jLabel3.setText("Nhãn hiệu");

        jLabel4.setText("Giá ");

        jLabel5.setText("Số lượng");

        jLabel7.setText("Category");

        jLabel6.setText("Size");

        txttensp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttenspKeyPressed(evt);
            }
        });

        txtbrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbrandKeyReleased(evt);
            }
        });

        txtsoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluongActionPerformed(evt);
            }
        });
        txtsoluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsoluongKeyPressed(evt);
            }
        });

        txtgia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgiaKeyPressed(evt);
            }
        });

        jButton1.setText("Thêm sản phẩm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Mã Sản phẩm");

        txtmasp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmaspKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmaspKeyReleased(evt);
            }
        });

        txtfind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfindKeyReleased(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jMenu6.setText("File");

        jMenu1.setText("Thay đổi thông tin đăng nhâp");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu6.add(jMenu1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Thoát");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Info");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Quản Lý");

        jMenu2.setText("Quản lý khách hàng");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu7.add(jMenu2);

        jMenu8.setText("Quản lý hóa đơn");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenu7.add(jMenu8);

        jMenu10.setText("Quản lý chi tiết hóa đơn");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenu7.add(jMenu10);

        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttensp, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtbrand)
                            .addComponent(txtmasp))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFind))
                        .addGap(2, 2, 2)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluongActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        listcate =catedll.getAll();
        listpro = prodll.getAll();
        int Proid= Integer.parseInt(txtmasp.getText());
        String Tensp= txttensp.getText();
        String brand= txtbrand.getText();
        int gia=Integer.parseInt(txtgia.getText());
        int soluong=Integer.parseInt(txtsoluong.getText());
       // int Des=cbSize.getSelectedIndex();
       String Des=String.valueOf(cbSize.getSelectedItem());
        int Cate= cbCate.getSelectedIndex();
        int row= tbproduct.getSelectedRow();
     //   int Desid=listpro.get(Des).getproid();
        int Cateid=listcate.get(Cate).getcatid();
        
        Product pr = new Product();
        pr.setproId(listpro.get(row).getproid());
        pr.setname(Tensp);
        pr.setbrand(brand);
        pr.setprice(gia);
        pr.setquantity(soluong);
        pr.setDesc(Des);
        pr.setcatid(Cateid);
        if(prodll.UpdateData(pr)){
            JOptionPane.showMessageDialog(this, "Update thành công");
            Bliding();
        }else{
            JOptionPane.showMessageDialog(this, "Update thất bại");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        listcate =catedll.getAll();
        listpro = prodll.getAll();
        int Proid= Integer.parseInt(txtmasp.getText());
        String Tensp= txttensp.getText();
        String brand= txtbrand.getText();
        int gia=Integer.parseInt(txtgia.getText());
        int soluong=Integer.parseInt(txtsoluong.getText());
       // int Des=cbSize.getSelectedIndex();
       String Des=String.valueOf(cbSize.getSelectedItem());
        int Cate= cbCate.getSelectedIndex();
        
     //   int Desid=listpro.get(Des).getproid();
        int Cateid=listcate.get(Cate).getcatid();
        
        Product pr = new Product();
        pr.setproId(Proid);
        pr.setname(Tensp);
        pr.setbrand(brand);
        pr.setprice(gia);
        pr.setquantity(soluong);
        pr.setDesc(Des);
        pr.setcatid(Cateid);
        if(prodll.Adddata(pr)){
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            Bliding();
        }else{
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproductMouseClicked
        // TODO add your handling code here:
        if(tbproduct.getSelectedRow()!=-1){
            int row=tbproduct.getSelectedRow();
            listpro=prodll.getAll();
            txtmasp.setText(String.valueOf(tbproduct.getValueAt(row, 0)));
            txttensp.setText(String.valueOf(tbproduct.getValueAt(row, 1)));
            txtbrand.setText(String.valueOf(tbproduct.getValueAt(row, 2)));
            txtgia.setText(String.valueOf(tbproduct.getValueAt(row, 3)));
            txtsoluong.setText(String.valueOf(tbproduct.getValueAt(row, 4)));
            //cbSize.addItem(String.valueOf(tbproduct.getValueAt(row, 5)));
            //cbCate.addItem(String.valueOf(tbproduct.getValueAt(row, 6)));
            cbSize.setSelectedItem(tbproduct.getValueAt(row, 5));
            cbCate.setSelectedItem(tbproduct.getValueAt(row, 6));
            
        }
        
     
       
        
        
    }//GEN-LAST:event_tbproductMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(tbproduct.getSelectedRow()!=-1){
            int row= tbproduct.getSelectedRow();
            listpro=prodll.getAll();
            
            if(prodll.DelData(listpro.get(row).getproid())){
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                Bliding();
            }
            else{
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kq=JOptionPane.showConfirmDialog(null, "Bạn thật sự muốn thoát","Close",JOptionPane.YES_OPTION);
        if(kq==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
      
     
           String find = txtfind.getText();
        
             DefaultTableModel dtm= (DefaultTableModel)tbproduct.getModel();
             dtm.fireTableDataChanged();
             TableRowSorter trs= new TableRowSorter(dtm);
             tbproduct.setRowSorter(trs);
             trs.setRowFilter(RowFilter.regexFilter(find));
             
      
      
    }//GEN-LAST:event_btnFindActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
       
        GuiUser us= new GuiUser();
        us.setVisible(true);
        this.setVisible(false);
       
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        // TODO add your handling code here:
        QLHOADON qlhd= new QLHOADON();
        qlhd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void txtfindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyPressed
        // TODO add your handling code here:
         
        
            
    }//GEN-LAST:event_txtfindKeyPressed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        // TODO add your handling code here:
        GuiOrderDetail orde= new GuiOrderDetail();
        orde.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu10MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        QuenPass qp= new QuenPass();
        qp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void txtmaspKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaspKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtmaspKeyPressed

    private void txtgiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgiaKeyPressed
        // TODO add your handling code here:ơngj 
        Pattern pattern =Pattern.compile("\\d*");
        Matcher matcher =pattern.matcher(txtgia.getText());
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(this, "Giá là số","Warning",JOptionPane.WARNING_MESSAGE);
            txtgia.requestFocus();
            txtgia.setText("");
        }
    }//GEN-LAST:event_txtgiaKeyPressed

    private void txtsoluongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsoluongKeyPressed
        // TODO add your handling code here:
        Pattern pattern =Pattern.compile("\\d*");
        Matcher matcher =pattern.matcher(txtsoluong.getText());
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(this, "Số lượng là số","Warning",JOptionPane.WARNING_MESSAGE);
            txtsoluong.requestFocus();
            txtsoluong.setText("");
        }
    }//GEN-LAST:event_txtsoluongKeyPressed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Phần mềm được làm bởi Hayashi Ngọc Long");
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Phần mềm đươc làm bởi Hayashi Ngọc Long");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void txttenspKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttenspKeyPressed
        // TODO add your handling code here:
        
       if(checkdll.checksyb(txttensp.getText())){
           JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt");
           txttensp.setText("");
       }
        
    }//GEN-LAST:event_txttenspKeyPressed

    private void txtbrandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbrandKeyReleased
        // TODO add your handling code here:
        if(checkdll.checksyb(txtbrand.getText())){
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt");
            txtbrand.setText("");
        }
    }//GEN-LAST:event_txtbrandKeyReleased

    private void txtfindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyReleased
        // TODO add your handling code here:
         DefaultTableModel dtm= (DefaultTableModel)tbproduct.getModel();
             dtm.fireTableDataChanged();
             TableRowSorter trs= new TableRowSorter(dtm);
             tbproduct.setRowSorter(trs);
             trs.setRowFilter(RowFilter.regexFilter(txtfind.getText()));
    }//GEN-LAST:event_txtfindKeyReleased

    private void txtmaspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaspKeyReleased
        // TODO add your handling code here:
         Pattern pattern =Pattern.compile("\\d*");
        Matcher matcher =pattern.matcher(txtmasp.getText());
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(this, "Giá là số","Warning",JOptionPane.WARNING_MESSAGE);
            txtmasp.requestFocus();
            txtmasp.setText("");
        }
         int row=tbproduct.getRowCount();
      int ma= row+1;
       
     /*  if(Integer.parseInt( txtmasp.getText())<ma)
       {
           
           JOptionPane.showMessageDialog(this, "Mã tăng và không được trùng mã có sẵn!");
           txtmasp.setText(Integer.toString(ma));
       }*/
        for(int i=0;i<row;i++){
            if(txtmasp.getText().equals(String.valueOf(tbproduct.getValueAt(i, 0)))){
                JOptionPane.showMessageDialog(this,"Không được trùng mã");
             // int ma1=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
               // txtmasp.setText(String.valueOf(ma1+1));
               txtmasp.setText("");
            }
        }
    }//GEN-LAST:event_txtmaspKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JComboBox<String> cbCate;
    private javax.swing.JComboBox<String> cbSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbproduct;
    private javax.swing.JTextField txtbrand;
    private javax.swing.JTextField txtfind;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttensp;
    // End of variables declaration//GEN-END:variables

    
}
