/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DLL.CheckKituDLL;
import DLL.OrderDLL;
import DLL.OrderDetailDLL;
import DLL.ProductDLL;
import DLL.UserDLL;
import Entity.Order;
import Entity.OrderDetail;
import Entity.Product;
import Entity.User;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ReportHoaDon.ReportHoaDon;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Aki
 */
public class QLHOADON extends javax.swing.JFrame {

    /**
     * Creates new form QLHOADON
     */
    OrderDLL orderdll= new OrderDLL();
    ArrayList<Order> listorder= new ArrayList<>();
    
    ProductDLL prodll= new ProductDLL();
    ArrayList<Product> listproduct= new ArrayList<>();
    
    UserDLL userdll= new UserDLL();
    ArrayList<User> listuser= new ArrayList<>();
    
    OrderDetailDLL oreddll= new OrderDetailDLL();
    ArrayList<OrderDetail> listorde= new ArrayList<>();
    
    CheckKituDLL checkdll= new CheckKituDLL();
    
    public QLHOADON() {
        initComponents();
        Bliding();
        BlidingUser();
        int row= tbshow.getRowCount();
         for(int i=1;i<row;i++){
           int max=Integer.parseInt(String.valueOf((tbshow.getValueAt(0, 0))));
            if(max<Integer.parseInt(String.valueOf(tbshow.getValueAt(i, 0)))){
                max=Integer.parseInt(String.valueOf(tbshow.getValueAt(i, 0)));
             
             // int ma1=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
               // txtmasp.setText(String.valueOf(ma1+1));
               //txtmasp.setText("");
            }
            max=max+1;
            txtMaHD.setText(String.valueOf(max));
        }
    }
    public void Bliding(){
        listorder= orderdll.getAll();
        Vector colums= new Vector();
        colums.add("Mã Hóa Đơn");
        
        colums.add("Tên hóa đơn");
       
    
        colums.add("Tên khách hàng");
  
        colums.add("Giá");
        colums.add("Ngày tạo");
        Vector data= new Vector();
        for(Order or:listorder){
            Vector row= new Vector();
            row.add(or.getOrderID());
            row.add(or.getName());
            listuser=userdll.getbyID(or.getUserID());
            if(listuser.size()>0){
                row.add(listuser.get(0).getFullname());
            }
            else{
                    row.add("Chua co du lieu");}
        
            row.add(or.getPrice());
            row.add(or.getDate());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data,colums);
        tbshow.setModel(dtm);
        
    }
    public void BlidingUser(){
        listuser=userdll.getAll();
        for(User us:listuser){
            cbTenKH.addItem(us.getFullname());
        }
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbshow = new javax.swing.JTable();
        txtMaHD = new javax.swing.JTextField();
        txtTenHD = new javax.swing.JTextField();
        txtGiatien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbTenKH = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtfind = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản lý hóa đơn");

        tbshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbshowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbshow);

        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });
        txtMaHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaHDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaHDKeyReleased(evt);
            }
        });

        txtTenHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenHDActionPerformed(evt);
            }
        });
        txtTenHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenHDKeyReleased(evt);
            }
        });

        txtGiatien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiatienActionPerformed(evt);
            }
        });
        txtGiatien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiatienKeyPressed(evt);
            }
        });

        jLabel2.setText("Mã Hóa Đơn");

        jLabel3.setText("Tên Hóa Đơn");

        jLabel6.setText("Giá tiên");

        jLabel8.setText("Khách hàng");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Ngày lập");

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        jLabel4.setText("VNĐ");

        jButton4.setText("Xuất Báo cáo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtfind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfindKeyReleased(evt);
            }
        });

        jButton5.setText("Find");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenu3.setText("jMenu3");
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenu4.setText("Quản lý sản phẩm");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu4);

        jMenu5.setText("Quản lý khách hàng");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu5);

        jMenuItem1.setText("Hóa đơn chi tiết");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(17, 17, 17))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenHD, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtMaHD))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel8)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtGiatien, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton4)
                                            .addComponent(jLabel4)))))
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiatien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(cbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void txtTenHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenHDActionPerformed

    private void txtGiatienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiatienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiatienActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        listorder=orderdll.getAll();
        listuser=userdll.getAll();
        int Mahd= Integer.parseInt(txtMaHD.getText());
        String Tenhd= txtTenHD.getText();
        String date=txtDate.getText();
        int gia=Integer.parseInt(txtGiatien.getText());
        int rowUser=cbTenKH.getSelectedIndex();
        
        int idUser=listuser.get(rowUser).getUserid();
        
        Order or= new Order();
        
        or.setOrderID(Mahd);
        or.setName(Tenhd);
        or.setUserID(idUser);
        or.setPrice(gia);
        or.setDate(date);
        if(orderdll.AddData(or)){
            JOptionPane.showMessageDialog(this, "Them thanh cong");
            Bliding();
        }else{
            JOptionPane.showMessageDialog(this, "Them that bai");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        listuser=userdll.getAll();
        listorder=orderdll.getAll();
        int Mahd= Integer.parseInt(txtMaHD.getText());
        String Tenhd= txtTenHD.getText();
        String date=txtDate.getText();
        int gia=Integer.parseInt(txtGiatien.getText());
        int row=tbshow.getSelectedRow();
        int rowUser=cbTenKH.getSelectedIndex();
        
        int idUser=listuser.get(rowUser).getUserid();
        
         Order or= new Order();
        
        or.setOrderID(listorder.get(row).getOrderID());
        or.setName(Tenhd);
        or.setUserID(idUser);
        or.setPrice(gia);
        or.setDate(date);
        if(orderdll.UpdateData(or)){
            JOptionPane.showMessageDialog(this, "Update thanh cong");
            Bliding();
        }else{
            JOptionPane.showMessageDialog(this, "Update that bai");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbshowMouseClicked
        // TODO add your handling code here:
        if(tbshow.getSelectedRow()!=-1){
            int row=tbshow.getSelectedRow();
            txtMaHD.setText(String.valueOf(tbshow.getValueAt(row, 0)));
            txtTenHD.setText(String.valueOf(tbshow.getValueAt(row, 1)));
            txtGiatien.setText(String.valueOf(tbshow.getValueAt(row, 3)));
            txtDate.setText(String.valueOf(tbshow.getValueAt(row, 4)));
            cbTenKH.setSelectedItem(tbshow.getValueAt(row, 2));
            /*listuser=userdll.getbyID((listuser.get(row).getUserid()));
            if(listuser.size()>0){
                cbTenKH.setSelectedItem(listuser.get(0).getFullname());
            }else{
                cbTenKH.setSelectedIndex(0);
                        
            }*/
        }
    }//GEN-LAST:event_tbshowMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(tbshow.getSelectedRow()!=-1){
            int row=tbshow.getSelectedRow();
            listorder=orderdll.getAll();
            
            if(orderdll.DelData(listorder.get(row).getOrderID())){
                JOptionPane.showMessageDialog(this, "Xoa thanh cong");
                Bliding();
            }else{
                JOptionPane.showMessageDialog(this, "Xoa that bai");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Moi chon dong can xoa");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:hat
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kq=JOptionPane.showConfirmDialog(null, "Ban that su muon thoat","Close",JOptionPane.YES_OPTION);
        if(kq==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        Main m= new Main();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        GuiUser user= new GuiUser();
        user.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     if(tbshow.getSelectedRow()!=-1){
         listuser=userdll.getAll();
        
         int row=tbshow.getSelectedRow();
         
         String username=String.valueOf(tbshow.getValueAt(row, 2));
         int rowuser=cbTenKH.getSelectedIndex();
         int userid=listuser.get(rowuser).getUserid();
         
         //int id=Integer.parseInt(String.valueOf(tbshow.getValueAt(row, 2)));
         
         
        
         
         
         
         ReportHoaDon reHD= new ReportHoaDon(userid);
         reHD.setVisible(true);
         
         
         
         
         
     }else{
         JOptionPane.showMessageDialog(this, "Moi chon dong!");
     }
        
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String find = txtfind.getText();
        
             DefaultTableModel dtm= (DefaultTableModel)tbshow.getModel();
             dtm.fireTableDataChanged();
             TableRowSorter trs= new TableRowSorter(dtm);
             tbshow.setRowSorter(trs);
             trs.setRowFilter(RowFilter.regexFilter(find));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtfindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyPressed
        // TODO add your handling code here:
       
        
             
    }//GEN-LAST:event_txtfindKeyPressed

    private void txtMaHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaHDKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtMaHDKeyPressed

    private void txtGiatienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiatienKeyPressed
        // TODO add your handling code here:
         Pattern pattern =Pattern.compile("\\d*");
        Matcher matcher =pattern.matcher(txtGiatien.getText());
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(this, "Giá là số","Warning",JOptionPane.WARNING_MESSAGE);
            txtGiatien.requestFocus();
            txtGiatien.setText("");
        }
    }//GEN-LAST:event_txtGiatienKeyPressed

    private void txtTenHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenHDKeyReleased
        // TODO add your handling code here:
         if(checkdll.checksyb(txtTenHD.getText())){
           JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt");
           txtTenHD.setText("");
       }
    }//GEN-LAST:event_txtTenHDKeyReleased

    private void txtfindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyReleased
        // TODO add your handling code here:
        DefaultTableModel dtm= (DefaultTableModel)tbshow.getModel();
             dtm.fireTableDataChanged();
             TableRowSorter trs= new TableRowSorter(dtm);
             tbshow.setRowSorter(trs);
             trs.setRowFilter(RowFilter.regexFilter(txtfind.getText()));
    }//GEN-LAST:event_txtfindKeyReleased

    private void txtMaHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaHDKeyReleased
        // TODO add your handling code here:
         Pattern pattern =Pattern.compile("\\d*");
        Matcher matcher =pattern.matcher(txtMaHD.getText());
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(this, "Mã là số","Warning",JOptionPane.WARNING_MESSAGE);
            txtMaHD.requestFocus();
            txtMaHD.setText("");
        }
           int row=tbshow.getRowCount();
      int ma= row+1;
       
     /*  if(Integer.parseInt( txtmasp.getText())<ma)
       {
           
           JOptionPane.showMessageDialog(this, "Mã tăng và không được trùng mã có sẵn!");
           txtmasp.setText(Integer.toString(ma));
       }*/
        for(int i=0;i<row;i++){
            if(txtMaHD.getText().equals(String.valueOf(tbshow.getValueAt(i, 0)))){
                JOptionPane.showMessageDialog(this,"Không được trùng mã");
             // int ma1=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
               // txtmasp.setText(String.valueOf(ma1+1));
               txtMaHD.setText("");
            }
        }
    }//GEN-LAST:event_txtMaHDKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        GuiOrderDetail guiod= new GuiOrderDetail();
        guiod.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHOADON().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTenKH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbshow;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtGiatien;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtTenHD;
    private javax.swing.JTextField txtfind;
    // End of variables declaration//GEN-END:variables
}
